name: py37airflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
      - apache-airflow[postgres,google]==2.3.0 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.3.0/constraints-3.7.txt"
      - flake8
      - flake8-docstrings
      - black
      - ipykernel
variables:
  AIRFLOW_HOME: /Users/davidhin/Documents/airflow-docker-local